-
  version: 1.0.{build}
  image: Visual Studio 2017
  configuration:
  - Release
  clone_folder: C:/openchemistry/avogadrolibs
  init:
  - cmd:
  environment:
    PATH: '%PATH%;%QTDIR%\bin'
    matrix:
    - CMAKE_GENERATOR: '"Ninja"'
      QTDIR: C:\Qt\5.6\msvc2015_64
      platform: x64

  build_script:
    - cmd: >-
        if %appveyor_repo_tag% equ false scripts\appveyor\build.bat
